name: Unit Tests

on:
  push:
  pull_request:

jobs:
  build-mswin:
    name: Win - Unit Tests
    runs-on: windows-latest

    strategy:
       matrix:
         levels: [-o0, -o1, -o2, -o3, -o4, -o5, -o6, -o7, -o8, -o9, -oFast, -oSize]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-rc.2.20479.15' # SDK Version to use; x will use the latest version of the 5.0 channel
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
      - name: Restore nuget Packages
        run: dotnet restore Mosa.sln
        working-directory: Source
      - name: Build
        run: dotnet build Source/Mosa.sln
      - name: Unit Tests
        run: bin\Mosa.Utility.UnitTests.exe ${{ matrix.level }} -s Emulator.Display=false

  build-unix:
    name: Linux - Unit Tests
    runs-on: ubuntu-latest

    strategy:
       matrix:
         levels: [-o0, -o1, -o2, -o3, -o4, -o5, -o6, -o7, -o8, -o9, -oFast, -oSize]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Restore nuget Packages
        run: dotnet restore Source/Mosa.Linux.sln
      - name: Build
        run: dotnet build Source/Mosa.Linux.sln
      - name: Update Package Respository
        run: sudo apt-get -y -o Acquire::Check-Valid-Until=false update
      - name: Install Qemu
        run: sudo apt-get install -y wget qemu qemu-system qemu-system-x86
      - name: Unit Tests
        run: dotnet bin/Mosa.Utility.UnitTests.dll ${{ matrix.level }} -s Emulator.Display=false
